export const keys = {
    processes: ['processes'],
    notices: ['notices'],
    notice: (id) => ['notices', id],
    parseQueue: ['parse-queue'],
    settings: ['settings'],
    products: ['products'],
    productList: (query) => ['products', 'list', JSON.stringify(query)],
    productFacets: ['products', 'facets'],
    product: (id) => ['products', 'card', id],
    catalogs: ['catalogs'],
    catalogList: ['catalogs', 'list'],
    orders: ['orders'],
    orderList: (search) => ['orders', 'list', search || ''],
    order: (id) => ['orders', 'card', id],
    priceRules: ['price-rules'],
    promo: ['promo'],
    services: ['services'],
    serviceTree: ['services', 'tree'],
    serviceCatalogs: ['services', 'catalogs'],
    serviceCodes: (offerId, status) => ['services', 'codes', offerId, status],
    structure: ['structure'],
    media: ['media'],
};

export const invalidatedBy = {
    'process.start': [keys.processes, keys.parseQueue],
    'process.cancel': [keys.processes, keys.parseQueue],
    'notice.dismiss': [keys.notices],
    'settings.write': [keys.settings],
    'product.write': [keys.products, keys.catalogs],
    'catalog.write': [keys.catalogs, keys.products],
    'order.write': [keys.orders],
    'price.write': [keys.priceRules, keys.products],
    'promo.write': [keys.promo],
    'service.write': [keys.services],
    'structure.write': [keys.structure],
    'media.write': [keys.media],
};
