export const keys = {
    processes: ['processes'],
    notices: ['notices'],
    notice: (id) => ['notices', id],
    parseQueue: ['parse-queue'],
    associationsSchedule: ['associations', 'schedule'],
    settings: ['settings'],
    sessions: ['admin-sessions'],
    overview: (range) => ['overview', range],
    products: ['products'],
    productList: (query) => ['products', 'list', JSON.stringify(query)],
    productFacets: ['products', 'facets'],
    product: (id) => ['products', 'card', id],
    catalogs: ['catalogs'],
    catalogList: ['catalogs', 'list'],
    orders: ['orders'],
    customerList: (query) => ['customers', 'list', JSON.stringify(query || {})],
    customer: (id) => ['customers', 'card', id],
    orderList: (query) => ['orders', 'list', JSON.stringify(query || {})],
    order: (id) => ['orders', 'card', id],
    priceRules: ['price-rules'],
    priceRuleSet: (platform) => ['price-rules', platform],
    promo: ['promo'],
    promoUsage: (id) => ['promo', 'usage', id],
    paymentRegistry: ['payment-registry'],
    broadcast: ['broadcast'],
    services: ['services'],
    serviceTree: ['services', 'tree'],
    serviceCatalogs: ['services', 'catalogs'],
    serviceCodes: (offerId, status) => ['services', 'codes', offerId, status],
    structure: ['structure'],
    pages: ['structure', 'pages'],
    pageBlocks: (pageId, group) => ['structure', 'blocks', pageId, group],
    previewCards: ['structure', 'preview-cards'],
    banners: ['structure', 'banners'],
    startPages: ['structure', 'start-pages'],
    infoBlocks: ['structure', 'info-blocks'],
    searchClues: ['structure', 'search-clues'],
    popular: ['structure', 'popular'],
    media: ['media'],
    mediaFolder: (path) => ['media', 'folder', path || ''],
};

export const invalidatedBy = {
    'process.start': [keys.processes, keys.parseQueue],
    'process.cancel': [keys.processes, keys.parseQueue],
    'notice.dismiss': [keys.notices],
    'settings.write': [keys.settings],
    'product.write': [keys.products, keys.catalogs],
    'catalog.write': [keys.catalogs, keys.products],
    'order.write': [keys.orders],
    'price.write': [keys.priceRules, keys.products],
    'promo.write': [keys.promo],
    'payment.write': [keys.paymentRegistry],
    'service.write': [keys.services],
    'structure.write': [keys.structure, keys.pages, keys.banners, keys.startPages],
    'media.write': [keys.media],
};
